spring:
  profiles:
    active: dev

  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port}

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

  mail:
    host: smtp.gmail.com
    port: ${spring.mail.port}
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    code:
      expire:
        time: ${spring.mail.expire.time}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  cloud:
    gcp:
      storage:
        credentials:
          location: ${spring.cloud.gcp.storage.credentials.location}
        project-id: ${spring.cloud.gcp.storage.project-id}
        bucket: ${spring.cloud.gcp.storage.bucket}

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 60MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

myapp:
  api-url: ${myapp.api-url}
  local-url: ${myapp.local-url}

jwt:
  secret: ${jwt.secret}

token:
  expire:
    time:
      access: ${token.expire.time.access}
      refresh: ${token.expire.time.refresh}

oauth:
  kakao:
    client-id: ${oauth.kakao.client-id}
    redirect-uri: ${oauth.kakao.redirect-uri}
    id-token-url: ${oauth.kakao.id-token-url}
  google:
    client-id: ${oauth.google.client-id}
    client-secret: ${oauth.google.client-secret}
    redirect-uri: ${oauth.google.redirect-uri}
    id-token-url: ${oauth.google.id-token-url}

image:
  default-project-image: ${spring.cloud.gcp.default.image}