spring:
  profiles:
    active: dev

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

  mail:
    host: smtp.gmail.com
    port: ${spring.mail.port}
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

myapp:
  api-url: ${myapp.api-url}
  local-url: ${myapp.local-url}

jwt:
  secret: ${jwt.secret}

token:
  expire:
    time:
      access: ${token.expire.time.access}
      refresh: ${token.expire.time.refresh}

oauth:
  kakao:
    client-id: ${oauth.kakao.client-id}
    redirect-uri: ${oauth.kakao.redirect-uri}
    id-token-url: ${oauth.kakao.id-token-url}
  google:
    client-id: ${oauth.google.client-id}
    client-secret: ${oauth.google.client-secret}
    redirect-uri: ${oauth.google.redirect-uri}
    id-token-url: ${oauth.google.id-token-url}